---
title: "nonlinear_regression"
author: "Jack Yan"
date: "4/3/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(tidyverse)
library(mgcv)
library(modelr)
library(corrplot)
```

```{r}
set.seed(123)
data = read.csv("./data/life_expectancy.csv") %>% as.tibble %>% 
  janitor::clean_names() %>% 
  na.omit() %>% 
  filter(year == 2013) %>% 
  select(-country, -year) 
dim(data)
data2 = read.csv("./data/life_expectancy.csv") %>% as.tibble %>% 
  janitor::clean_names() %>% 
  na.omit() %>% 
  filter(year == 2013 | year == 2009 | year == 2000) %>% 
  select(-country, -year)

data_all = read.csv("./data/life_expectancy.csv") %>% as.tibble %>% 
  janitor::clean_names() %>% 
  na.omit() 
  select(-year, -country)

gam.fit <- train(x, y,
                 method = "gam",
                 tuneGrid = data.frame(method = "GCV.Cp", select = c(TRUE,FALSE)), 
                 trControl = ctrl1)
```

```{r}
trRows = createFolds(data$life_expectancy, k = 10, list = FALSE)

train_data = data[trRows,]
test_data = data[-trRows,]
```

### Scatter Plots
```{r}
names(data)
# matrix of predictors
x <- model.matrix(life_expectancy~., data)[,-1]
# vector of response
y <- data$life_expectancy
```

```{r}
theme1 <- trellis.par.get()
theme1$plot.symbol$col <- rgb(.2, .4, .2, .5) 
theme1$plot.symbol$pch <- 16
theme1$plot.line$col <- rgb(.8, .1, .1, 1) 
theme1$plot.line$lwd <- 2
theme1$strip.background$col <- rgb(.0, .2, .6, .2) 
trellis.par.set(theme1)
data_rename = data %>% 
  rename(income = income_composition_of_resources,
         per_expend = percentage_expenditure,
         to_expend = total_expenditure,
         death5 = under_five_deaths,
         thin5_9 = thinness_5_9_years,
         thin1_19 = thinness_1_19_years)
x_rename <- model.matrix(life_expectancy~., data_rename)[,-1]
# vector of response
names(data)
featurePlot(x_rename, y, plot = "scatter", labels = c("","Y"),
            type = c("p"), 
            layout = c(3, 7)
            )
par(cex = 0.7)
corrplot(cor(x_rename), tl.srt = 45, order = 'hclust', type = 'upper')
corrplot(cor(x), method='square')
```

### GAM

```{r, eval = F}
names(data)

fit.gamm = gamm(data = data_all,
                correlation = corExp(form = ~1 | country),
                life_expectancy ~ 
                  status + s(adult_mortality) + s(infant_deaths) + s(alcohol) + s(percentage_expenditure) +
                s(hepatitis_b) + s(measles) + s(bmi) + s(under_five_deaths) + s(polio) +
                s(total_expenditure) + s(diphtheria) + s(hiv_aids) + s(gdp) + s(population) +
                s(thinness_1_19_years) + s(thinness_5_9_years) 
              )

summary(fit.gamm)

fit.gam1 = gam(data = data, 
              life_expectancy ~ 
                status + s(adult_mortality) + s(infant_deaths) + s(alcohol) +  s(percentage_expenditure) +
                s(bmi) + s(under_five_deaths) +
                s(total_expenditure) + s(diphtheria) + s(hiv_aids) + s(gdp) + s(population) +
                s(thinness_1_19_years)
              )
summary(fit.gam1)

fit.gam2 = gam(data = data, 
                life_expectancy ~ 
                status + s(adult_mortality) + infant_deaths + s(alcohol) + s(percentage_expenditure) +
                s(bmi) + under_five_deaths +
                total_expenditure + diphtheria + s(hiv_aids) + gdp + s(population) +
                s(thinness_1_19_years)+ s(schooling) + s(income_composition_of_resources)
              )
summary(fit.gam2)
```


```{r}
names(data)
ctrl1 <- trainControl(method = "cv", number = 10)
data2 = data_all %>% filter()
x <- model.matrix(data = data, 
                  life_expectancy ~ status + adult_mortality + infant_deaths + alcohol + percentage_expenditure + 
                    hepatitis_b + measles + bmi + under_five_deaths + polio + diphtheria +
                    hiv_aids + thinness_1_19_years + thinness_5_9_years + income_composition_of_resources +
                    schooling)[,-1]

x <- model.matrix(data = data2, 
                  life_expectancy ~ status + adult_mortality + infant_deaths + alcohol + percentage_expenditure + 
                    hepatitis_b + measles + bmi + under_five_deaths + polio + total_expenditure + diphtheria +
                    hiv_aids + gdp + population + thinness_5_9_years + thinness_5_9_years + income_composition_of_resources +
                    schooling)[,-1]

y <- data2$life_expectancy
set.seed(2)
gam.fit <- train(x, y,
                 method = "gam",
                 tuneGrid = data.frame(method = "GCV.Cp", select = c(TRUE,FALSE)), 
                 trControl = ctrl1)

gam.fit$bestTune
# using feature selection, you get a better model.

gam.fit$finalModel
# using feature selection, the covarate with df=0 is discarded.

fit.gam2 = 
  gam(data = data, 
    life_expectancy ~ status + s(diphtheria) + s(polio) + 
    s(schooling) + s(infant_deaths) + s(hiv_aids) + s(thinness_5_9_years) + 
    s(under_five_deaths) + s(adult_mortality) + s(bmi) + s(income_composition_of_resources) + 
    s(total_expenditure) + s(alcohol) + s(percentage_expenditure) + 
    s(population) + s(gdp)
  )
summary(fit.gam2)

fit.gam2 = 
  gam(data = data, 
    life_expectancy ~ status + s(hiv_aids) + s(diphtheria) + polio + 
    infant_deaths + under_five_deaths + s(thinness_5_9_years) + 
    s(schooling) + s(alcohol) + s(adult_mortality) + s(bmi) + 
    s(income_composition_of_resources) + s(percentage_expenditure)
  )
summary(fit.gam2)
```

```{r}
x <- model.matrix(data = data, 
                  life_expectancy ~ status + adult_mortality + infant_deaths + alcohol + 
                    hepatitis_b + measles + bmi + under_five_deaths + total_expenditure + diphtheria +
                    hiv_aids + gdp + population + thinness_5_9_years + thinness_5_9_years + income_composition_of_resources +
                    schooling)[,-1]
y = data$life_expectancy
gam.fit <- train(x, y,
                 method = "gam",
                 tuneGrid = data.frame(method = "GCV.Cp", select = c(TRUE,FALSE)), 
                 trControl = ctrl1)
gam.fit$finalModel
```

```{r}
# This is the final model for GAM
fit.gam3 = gam(data = data, 
              life_expectancy ~ 
                s(adult_mortality) + s(bmi) + s(total_expenditure) + s(hiv_aids) + s(total_expenditure) +
                s(thinness_1_19_years) + s(schooling) + s(income_composition_of_resources)
              )
summary(fit.gam3)
par(mfrow = c(3, 3))
plot(fit.gam3)
```

### MARS 
```{r}
mars_grid <- expand.grid(degree = 1:5, 
                         nprune = 2:20)

set.seed(2)
mars.fit <- train(x, y,
                 method = "earth",
                 tuneGrid = mars_grid,
                 trControl = ctrl1)

ggplot(mars.fit)

mars.fit$bestTune

coef(mars.fit$finalModel) 
```

Final model of MARS
```{r}
# This is the final model of MARS
fit_earth = 
  earth(life_expectancy~.,
        degree = 1,
        nprune = 8,
        data = data)
summary(fit_earth)
```

## KNN
```{r}
ctrl2 <- trainControl(method = "cv", number = 20)
knn.fit <- train(x, y,
                 method = "knn",
                 tuneLength = 80,
                 trControl = ctrl2)
knn.fit 

knn.fit <- train(x, y,
                 method = "knn",
                 tuneLength = 100,
                 trControl = ctrl2)
knn.fit

predict(knn.fit)
```
















## Cross-validation
```{r}
set.seed(123123)
cv_df = 
  crossv_mc(data, 10) %>% 
  mutate(train = map(train, as_tibble),
         test = map(test, as_tibble))
# cv_df =  
#   cv_df %>%  
#   mutate(train_x = map(train, ~model.matrix(life_expectancy~., .x)[,-1])) %>% 
#   mutate(train_y = map(train, ~.x$life_expectancy)) %>% 
#   mutate(test_x = map(test, ~model.matrix(life_expectancy~., .x)[,-1])) %>% 
#   mutate(test_y = map(test, ~.x$life_expectancy))  

mars_grid <- expand.grid(degree = 1:2, 
                         nprune = 2:20)
ctrl1 = trainControl(method = "cv", number = 10)
ctrl2 <- trainControl(method = "cv", number = 20)
# MARS
cv_df = 
  cv_df %>% 
  mutate(earth_mod = map(train, ~train(data = .x,
                 life_expectancy~.,
                 method = "earth",
                 tuneGrid = mars_grid,
                 trControl = ctrl1)),
         earth_tune = map(earth_mod, ~.$bestTune),
         rmse_earth = map2_dbl(earth_mod, test, ~rmse(model = .x, data = .y))
         ) 
# KNN
cv_df = 
  cv_df %>% 
  mutate(knn_mod = map(train, 
                ~train(data = .x,
                 life_expectancy~.,
                 method = "knn",
                 tuneLength = 100,
                 trControl = ctrl2)),
         knn_tune = map(knn_mod, ~.$bestTune),
         rmse_knn = map2_dbl(knn_mod, test, ~rmse(model = .x, data = .y))
         ) 

cv_df %>% pull(earth_tune)
cv_df %>% pull(knn_tune)

# LM
cv_df = 
  cv_df %>% 
  mutate(lm_mod = map(train, ~lm(life_expectancy~., data = .x)),
         rmse_lm = map2_dbl(lm_mod, test, ~rmse(model = .x, data = .y))) 
# Ridge
cv_df = 
  cv_df %>% 
  mutate(ridge_mod = map(train, ~train(data = .x, 
                  life_expectancy~.,
                  method = "glmnet",
                  tuneGrid = expand.grid(alpha = 0, lambda = exp(seq(-1, 1, length=100))),
                  trControl = ctrl1)),
         rmse_ridge = map2_dbl(ridge_mod, test, ~rmse(model = .x, data = .y)))

# The lasso
cv_df = 
  cv_df %>% 
  mutate(lasso_mod = map(train, ~train(data = .x, 
                  life_expectancy~.,
                  method = "glmnet",
                  tuneGrid = expand.grid(alpha = 1, lambda = exp(seq(-5, 1, length=100))),
                  trControl = ctrl1,
                  preProc = c("center", "scale"))),
         rmse_lasso = map2_dbl(lasso_mod, test, ~rmse(model = .x, data = .y)))

# PCR

cv_df = 
  cv_df %>% 
  mutate(pcr_mod = map(train, ~train(data = .x, 
                  life_expectancy~.,
                  method = "pcr",
                  tuneGrid = data.frame(ncomp = seq(1:18)),
                  trControl = ctrl1,
                  scale = TRUE)),
         rmse_pcr = map2_dbl(pcr_mod, test, ~rmse(model = .x, data = .y)))


cv_df %>% 
  select(rmse_earth, rmse_knn, rmse_lm, rmse_ridge, rmse_lasso, rmse_pcr)

cv_df %>% 
  select(starts_with("rmse")) %>% 
  gather(key = model, value = rmse) %>% 
  mutate(model = str_replace(model, "rmse_", ""),
         model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```


